services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - favorites-data:/var/lib/postgresql/data
    networks:
      - favorites-network
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - favorites-network
  api:
    build:
      context: .
      dockerfile: ./dockerfile
    image: favorites-api:local
    container_name: favorites-api
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 10
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    networks:
      - favorites-network

networks:
  favorites-network:
    driver: bridge
volumes:
  favorites-data: